### ISSUE TITLE
Hover messages not working in 1.4.9 | issue with displaying color codes with placeholder %player_name%

### ISSUE THREAD

**Issue by Ajneb97** [nonxedy/nonchat#7]
Hello, in the latest version of nonchat (1.4.9), it seems hover messages are not working at all. Tested with 1.4.8 and they do work.

This is the output of the /version command on my server:
This server is running Paper version 1.21.4-232-ver/1.21.4@12d8fe0 (2025-06-09T10:15:42Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

**Comment by Ajneb97** [comment]
that's the version I am using.

**Comment by nonxedy** [comment]
weird, PlaceholderAPI installed on ur server?

**Comment by Ajneb97** [comment]
Yes it's installed, but as I say, the whole tooltip doesn't appear when I put the cursor on the message. This works correctly on the previous version.

**Comment by nonxedy** [comment]
but I have no such issue on my test server, what plugins do u have installed?

**Comment by Ajneb97** [comment]
![Image](https://github.com/user-attachments/assets/990e6f79-40ee-4c62-9a94-59219b639aa4)
This is my config:
```
# ==================================================
# NONCHAT CONFIGURATION FILE
# Plugin created by nonxedy (@nonxedy).
# Published on github https://github.com/nonxedy/nonchat
# Published on modrinth https://modrinth.com/plugin/nonchat
# Version of the plugin: 1.4.9
#
# - LuckPerms support.
# - Vault support.
# - PlaceHolderAPI support.
# - DiscordSRV support.
# ==================================================
# CUSTOM CHANNELS
# You can create your own custom channels in several ways:
#
# 1. Adding them to this config file:
#    Copy and modify one of the existing channel blocks under the "channels:" section.
#    Make sure to use a unique ID and set all the parameters you need.
#
# 2. Using the in-game command (requires nonchat.admin.channel.create permission):
#    /channel create <id> <display-name> [options]
#    
# Available options for channels:
#   enabled: true/false         - Whether the channel is enabled
#   display-name: "Name"        - Display name shown in messages and listings
#   format: "text {placeholders}" - The message format (must include {message})
#   radius: number              - Chat radius in blocks, -1 for global
#   character: 'X'              - Trigger character (prefix) for this channel
#   send-permission: "perm"     - Permission needed to send messages
#   receive-permission: "perm"  - Permission needed to receive messages
#   cooldown: number            - Seconds between messages (0 for no cooldown)
#   min-length: number          - Minimum message length (0 for no minimum)
#   max-length: number          - Maximum message length (-1 for unlimited)
#
# Command options format:
#   format:text %luckperms_prefix% %player_name% {message}
#   char:X                      - Trigger character
#   send:permission.node        - Permission to send
#   receive:permission.node     - Permission to receive
#   radius:100                  - Radius in blocks (-1 for global)
#   enabled:true                - Enable/disable
#   cooldown:5                  - Cooldown in seconds
#   min:1                       - Min message length
#   max:100                     - Max message length
# ==================================================
# CHAT FORMATTING:
#
# {message} - The message (required)
# PlaceholderAPI placeholders
#
# !!! DONT DELETE {message} IF YOU DELETE IT, YOUR SENT MESSAGES WILL BE INVISIBLE !!!
# ==================================================

language: en # Supported: en, ru

debug: false # Enable/disable debug mode

update-checker: true # Enable/disable the update checker.

# Default channel that players will use when they join
default-channel: "global"

# The channels configuration.
channels:
  global: # The ID of the channel
    enabled: true # Enable/disable the channel
    display-name: "Global" # Display name for the channel
    format: "%luckperms_prefix%%player_displayname%§8: §f{message}" # The chat format
    radius: -1 # The radius of chat (in blocks). -1 = global
    character: '' # The character that triggers this channel
    send-permission: "" # Permission to send messages in this channel (empty = everyone)
    receive-permission: "" # Permission to receive messages from this channel (empty = everyone)
    cooldown: 2 # Cooldown between messages in seconds (0 = no cooldown)
    min-length: 0 # Minimum message length (0 = no minimum)
    max-length: -1 # Maximum message length (-1 to disable limit)
  
  staff:
    enabled: true
    display-name: "Staff"
    format: "§7(§bSC§7)§r %luckperms_prefix%%player_displayname%§r %luckperms_suffix%§7: §f{message}"
    radius: -1
    character: '*'
    send-permission: "nonchat.chat.staff"
    receive-permission: "nonchat.chat.staff"
    cooldown: 0
    min-length: 0
    max-length: -1

# The death config.
death:
  enabled: false # Enable/disable custom death messages
  format: "%luckperms_prefix% §f%player_name%§r %luckperms_suffix%§f died" # The death format.
  show-coordinates: false # Show death coordinates to the player

# The join/quit message config.
join-messages:
  enabled: true # Enable/disable join messages
  format: "§8(§a+§8) %luckperms_prefix%%player_displayname%" # Join message format

quit-messages:
  enabled: true # Enable/disable quit messages
  format: "§8(§c-§8) %luckperms_prefix%%player_displayname%" # Quit message format

# The private chat config.
private-chat-format: "§f{sender} §7-> §f{target}§7: §7{message}" # The private chat format.

# The spy command config.
spy-format: "§f{sender} §7-> §f{target}§7: §7{message}" # The spy command format.

# ==================================================
# BROADCAST CONFIGURATION
# Broadcast messages are messages that are sent to all players on the server.
# These messages are sent by the server and are not sent by players.
# ==================================================

broadcast:

  # Enable random auto broadcast messages.
  random: false

  # Example auto broadcast message.
  example:
    enabled: false # Will message shown?
    message: "This message will be sent every 60 seconds" # Message
    interval: 60 # Interval in seconds! Message will sent after X seconds.

# ==================================================
# CHAT BUBBLE CONFIGURATION
# Chat bubbles are small messages that appear above the player's head when they speak.
# ==================================================

chat-bubbles:
  enabled: false # Enable chat bubbles
  duration: 5 # Duration of the bubble in seconds.
  height: 2.5 # Height of the bubble in blocks.

# ==================================================
# ROLEPLAY COMMANDS
# Roleplay commands are commands that are used to simulate roleplay in the game.
# ==================================================

roleplay-commands: # List of roleplay commands.


# ==================================================
# HOVER TEXT
# Hover text are texts that are performed when a player hovers over a player's name in chat.
# ==================================================
hover-text:
  enabled: true # Enable/disable the hover text.
  format:
    - "&#FFAFFB⭐ %player_name%" # Player name
    - "&#FFAFFB► Rank: &#FFFFFF%luckperms_prefix%" # Prefix in luckperms
    - "&#FFAFFB► Balance: &#FFFFFF$%vault_eco_balance%" # Balance in vault
    - "&#FFAFFB► Level: &#FFFFFF%player_level%" # Level in minecraft
    - "&#FFAFFB► Playtime: &#FFFFFF%statistic_time_played%" # Playtime in PlaceholderAPI
    - "&#FFAFFB► Location: &#FFFFFF%player_world%" # Location in PlaceholderAPI
    - "&#FFAFFB► Ping: &#FFFFFF%player_ping%ms" # Ping in PlaceholderAPI

# ==================================================
# BLOCKED WORDS
# That is the list of banned words. Player will not be able to send messages with banned words.
# ==================================================
banned-words: # List of banned words.
  - "spam"
  - "badword"
  - "anotherbadword"
  - "плохой"

# ==================================================
# CAPS FILTER
# Caps filter is a feature that checks if the message contains too many capital letters.
# ==================================================
caps-filter:
  enabled: true # Enable/disable the caps filter.
  max-caps-percentage: 70 # Maximum percentage of capital letters allowed in a message.
  min-length: 4 # Minimum message length to check for caps.

```

**Comment by Ajneb97** [comment]
When I use %player_name% the variable displays the player name in white color, no matter what color code I use its always white.

**Comment by nonxedy** [comment]
Alr, I fixed that issue. U can build dev version of plugin in dev branch

**Comment by Ajneb97** [comment]
Sorry for bothering again but still having the same issue. The %player_name% or %player_displayname% variable is displaying in white, no matter what color code I use. For example:
format: "&8[&a%scorpionscore_level%&8] %luckperms_prefix%%player_name%§7: §f{message}"
or 
format: "&8[&a%scorpionscore_level%&8] &6%player_name%§7: §f{message}"

It seems it's only happening with the player variable.

**Comment by nonxedy** [comment]
Unfortunately, I have some problems with connecting to the local server, because of which I can not test the plugin updates, I do not know how much longer this will continue

**Comment by nonxedy** [comment]
nvm, fixed it lol

**Comment by nonxedy** [comment]
Alr, I fixed it in dev. version of plugin

**Comment by jorgesam8** [comment]
Hello, I wanted to let you know that I'm also having the same problem. I'm using NonChat 1.5.5 on a Purpur-1.21-2284 server. These are my plugins, and this is an example of the error I encountered:
-Fadah-Bukkit-3.2.0.jar
-AdvancedSkills-1.5.23.jar
-aiLeaderboards-2.10.1.jar
-AxGraves-1.2.3.jar
-Back-1.8.6.jar
-BetterRTP-3.12.0.jar
-CelestCombat-1.0.9.jar
-Clearlag-3.2.2.jar
-ClickTpa-v1.7.8.jar
-CoreSpawnX-1.0.6-BETA.jar
-DeathMessages-2.jar
-DecentHolograms-2.9.8.jar
-DonutHome-1.jar
-FastAsyncWorldEdit-Bukkit-2.12.2.jar
-GemsEconomy-4.9.2.jar
-GSit-24.1.jar
-Hat-1.5.0.jar
-ItemsAdder-4.0.3.jar
-LiteAnnouncer-1.3.4.0.jar
-LoneLibs-1.0.65.jar
-LumberJack-5.4.0.jar
-multiverse-core-5.3.3.jar
-nonchat-1.5.5.jar
-PlaceholderAPI-2.11.6.jar
-ProtectionStones-2.10.4.jar
-ProtocolLib.jar
-ReanBounties-1.0.jar
-RPGhuds_1.2.0-f2.jar
-Suicide-1.5.1.jar	
-TAB v5.3.2.jar
-TerraFormGenerator-24.1.0.jar
-UltimateClans-8.2.1.jar
-VaultUnlocked-2.17.0.jar
-ViaVersion-5.1.1.jar
-WorldBorder-1.2.1.jar
-worldguard-bukkit-7.0.12-dist.jar

<img width="622" height="415" alt="Image" src="https://github.com/user-attachments/assets/0d248eac-2937-43c7-bf77-5aef552c15af" />
